import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout';
import { useProductContext } from '../context';
import ProductList from '../components/ProductList';

export default function Home() {
  const [{ product }, { setProduct }] = useProductContext();

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center flex-1 flex-shrink-0 justify-center space-y-4 pt-10">
        <div className='text-lg'>
          Product List
        </div>
        <ProductList
          products={product}
        />
      </div>
    </Layout>
  )
}
